export const DATA = [
  {
    cuisineType: "Chinese",
    desc: "Hic.",
    dietaryChoice: "Vegan",
    favoriteCount: 171,
    id: 1,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Erjyguu",
    photo: "https://picsum.photos/seed/40587/305/160",
    price: 97,
  },
  {
    cuisineType: "Indian",
    desc: "Vel.",
    dietaryChoice: "Lactose Free",
    favoriteCount: 59,
    id: 2,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Nextuj",
    photo: "https://picsum.photos/seed/66938/305/160",
    price: 35,
  },
  {
    cuisineType: "Japanese",
    desc: ".",
    dietaryChoice: "Vegan",
    favoriteCount: 62,
    id: 3,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Wosfepks",
    photo: "https://picsum.photos/seed/25918/305/160",
    price: 53,
  },
  {
    cuisineType: "Indian",
    desc: ".",
    dietaryChoice: "Vegetarian",
    favoriteCount: 100,
    id: 4,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Sxdzqt",
    photo: "https://picsum.photos/seed/71056/305/160",
    price: 82,
  },
  {
    cuisineType: "Chinese",
    desc: "Ea.",
    dietaryChoice: "Gluten Free",
    favoriteCount: 116,
    id: 5,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Lsbmufwc",
    photo: "https://picsum.photos/seed/14134/305/160",
    price: 183,
  },
  {
    cuisineType: "Italian",
    desc: "A.",
    dietaryChoice: "Vegan",
    favoriteCount: 23,
    id: 6,
    isPublished: false,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Rczrxfq",
    photo: "https://picsum.photos/seed/33711/305/160",
    price: 151,
  },
  {
    cuisineType: "French",
    desc: "Et.",
    dietaryChoice: "Vegetarian",
    favoriteCount: 45,
    id: 7,
    isPublished: false,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Qwaqdbax",
    photo: "https://picsum.photos/seed/40108/305/160",
    price: 39,
  },
  {
    cuisineType: "Indian",
    desc: "Aut.",
    dietaryChoice: "Vegan",
    favoriteCount: 104,
    id: 8,
    isPublished: false,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Dptcbkwmz",
    photo: "https://picsum.photos/seed/38006/305/160",
    price: 157,
  },
  {
    cuisineType: "Indian",
    desc: ".",
    dietaryChoice: "Vegan",
    favoriteCount: 150,
    id: 9,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Cktzbvhd",
    photo: "https://picsum.photos/seed/30159/305/160",
    price: 61,
  },
  {
    cuisineType: "Italian",
    desc: "Ab.",
    dietaryChoice: "Gluten Free",
    favoriteCount: 78,
    id: 10,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Wammhqvg",
    photo: "https://picsum.photos/seed/28105/305/160",
    price: 9,
  },
  {
    cuisineType: "Chinese",
    desc: ".",
    dietaryChoice: "Vegetarian",
    favoriteCount: 161,
    id: 11,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Yuyfxsap",
    photo: "https://picsum.photos/seed/50312/305/160",
    price: 140,
  },
  {
    cuisineType: "Japanese",
    desc: "A.",
    dietaryChoice: "Lactose Free",
    favoriteCount: 174,
    id: 12,
    isPublished: false,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Xmgefjo",
    photo: "https://picsum.photos/seed/80329/305/160",
    price: 146,
  },
  {
    cuisineType: "Chinese",
    desc: "A a.",
    dietaryChoice: "Lactose Free",
    favoriteCount: 138,
    id: 13,
    isPublished: false,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Qfuaklh",
    photo: "https://picsum.photos/seed/52820/305/160",
    price: 106,
  },
  {
    cuisineType: "Indian",
    desc: ".",
    dietaryChoice: "Lactose Free",
    favoriteCount: 3,
    id: 14,
    isPublished: false,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Kunewpnc",
    photo: "https://picsum.photos/seed/03877/305/160",
    price: 90,
  },
  {
    cuisineType: "Indian",
    desc: "A.",
    dietaryChoice: "Vegan",
    favoriteCount: 35,
    id: 15,
    isPublished: true,
    kitchen: {
      desc: "a asperiores itaque",
      id: 1,
      name: "l8Qvs65FP2",
      status: "pending",
    },
    name: "Bthrljq",
    photo: "https://picsum.photos/seed/44264/305/160",
    price: 20,
  },
];
